import Head from "next/head";
import Script from "next/script";
import Landing from "../../Components/EventPage/Landing";
import { FluidContainer } from "../../Components/FluidContainer/FluidContainer";

function Event() {
  return (
    <>
      <Head>
        <title>Pandora Tech Festival | Newton School Coding Club | Pimpri Chinchwad College of Engineering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FluidContainer />
      <Landing />
    </>
  );
}

export default Event;
