import Head from "next/head";
import Content from "../../../Components/PraxisPage/Content";

function PraxisPage() {
  return (
    <>
      <Head>
        <title>NSCC - PRAXIS Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content />
    </>
  );
}

export default PraxisPage;
